# Generated by Django 5.0.7 on 2024-11-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
